name: rm
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  #pdf: ^3.8.2
  #share_extend: ^1.1.9
  path_provider: ^2.0.15
  printing:

  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.4.0
  intl: ^0.18.0
  provider: ^6.0.5
  http: ^0.13.3
  dropdown_button2: ^1.9.2
  #flutter_launcher_icons: ^0.12.0
  shared_preferences: #2.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.17.1
  #get: ^4.6.5

flutter_icons:
  android: true
  image_path: "dev_assets/LogoRM.png"
  adaptative_icon_background: "#ffffff"
  adaptative_icon_foreground: "dev_assets/iconeRM.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: open-sans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
